<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>

        <!-- Nuget Global Metadata -->
        <Title>DevSource.Foundation</Title>
        <Description>DevSource Foundation is a lightweight .NET foundation library for building cloud-native applications with clear architectural boundaries. It provides reusable primitives, domain building blocks, provider-agnostic repository contracts, and an extensible specification system for filtering, sorting, pagination, projection, and query composition.</Description>
        <Authors>DevSource Team</Authors>
        <Company>DevSource</Company>
        <PackageProjectUrl>https://github.com/Devsourceio/devsource-foundation</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Devsourceio/devsource-foundation</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>DDD, best-practices, bestpractices</PackageTags>
        <Version>2.0.0</Version>
    </PropertyGroup>    
</Project>
